version: '3'

services:
  db:
    container_name: smlt-bot-db
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped

  bot:
    container_name: smlt-bot
    build:
      context: .
    restart: unless-stopped
    environment:
      DB_HOST: db
    depends_on:
      - db
    command: python main.py


volumes:
  db: { }